apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtas-operator-bundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtas-operator-bundle
    app.kubernetes.io/part-of: operator
  name: rhtas-operator-bundle
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhtas-operator-bundle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhtas-operator-bundle
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator-bundle@sha256:8a3900bc9bdd1573f5afb2e5e90a96b1deec0963c7e4bff20461574d2496fc50
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
