apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtas-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator@sha256:8e9dcffc795ceee93b9962bf4a93e9429dacced5199a2d920d8cf778a046ef71
        name: container-image
        resources: {}
status: {}
